theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  menu:
    dropdown:
      linkToLevel1: true
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: false
  posts:
    index:
      layout: grid