theme: osuny
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  menu:
    dropdown:
      linkToLevel1: true
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: false
  posts:
    index:
      layout: grid