theme: osuny
_merge: deep
params:
  menu:
    primary:
      level_2:
        title:
          active: true
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  search:
    active: false
  posts:
    index:
      layout: grid