[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/portfolio/"
to = "/photographies/"

[[redirects]]
from = "/blog/"
to = "/ressources/"

[[redirects]]
from = "/portfolio/2014-mockba-la-blanche/"
to = "/photographies/2014-russie-nebuleuse/"

[[redirects]]
from = "/portfolio/2006-voyage-mexicain/"
to = "/photographies/2006-voyage-mexicain/"

[[redirects]]
from = "/portfolio/2014-rossiya-la-blanche/"
to = "/photographies/2014-rossiya-la-blanche/"

[[redirects]]
from = "/photographie/"
to = "/photographies/"

[[redirects]]
from = "/photographies/0-camino-frances/"
to = "/photographies/2008-camino-frances/"

[[redirects]]
from = "/equipe-editoriale/"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/portfolio/2014-russie-nebuleuse/"
to = "/photographies/2014-russie-nebuleuse/"

[[redirects]]
from = "/a-propos/"
to = "/contact/"

[[redirects]]
from = "/equipe/marion-rebier/actualites/"
to = "/equipe/marion-rebier/ressources/"

[[redirects]]
from = "/portfolio/2014-neiges-de-russie/"
to = "/photographies/2014-rossiya-la-blanche/"

[[redirects]]
from = "/portfolio/2014-baikal-une-lumiere/"
to = "/photographies/2014-baikal-une-lumiere/"

[[redirects]]
from = "/beelearning/ressources/"
to = "/ressources/"

[[redirects]]
from = "/equipe/marion-rebier/blog/"
to = "/equipe/marion-rebier/ressources/"

[[redirects]]
from = "/projets/"
to = "/photographies/"

[[redirects]]
from = "/portfolio/2006-heros-zapatistes/"
to = "/photographies/2006-heros-zapatistes/"

[[redirects]]
from = "/actualites/"
to = "/ressources/"

