[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/portfolio/index.html"
to = "/photographies/"

[[redirects]]
from = "/blog/index.html"
to = "/ressources/"

[[redirects]]
from = "/portfolio/2014-mockba-la-blanche/index.html"
to = "/photographies/2014-russie-nebuleuse/"

[[redirects]]
from = "/portfolio/2006-voyage-mexicain/index.html"
to = "/photographies/2006-voyage-mexicain/"

[[redirects]]
from = "/portfolio/2014-rossiya-la-blanche/index.html"
to = "/photographies/2014-rossiya-la-blanche/"

[[redirects]]
from = "/photographie/index.html"
to = "/photographies/"

[[redirects]]
from = "/photographies/0-camino-frances/index.html"
to = "/photographies/2008-camino-frances/"

[[redirects]]
from = "/equipe-editoriale/index.html"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/portfolio/2014-russie-nebuleuse/index.html"
to = "/photographies/2014-russie-nebuleuse/"

[[redirects]]
from = "/a-propos/index.html"
to = "/contact/"

[[redirects]]
from = "/equipe/marion-rebier/actualites/index.html"
to = "/equipe/marion-rebier/ressources/"

[[redirects]]
from = "/portfolio/2014-neiges-de-russie/index.html"
to = "/photographies/2014-rossiya-la-blanche/"

[[redirects]]
from = "/portfolio/2014-baikal-une-lumiere/index.html"
to = "/photographies/2014-baikal-une-lumiere/"

[[redirects]]
from = "/beelearning/ressources/index.html"
to = "/ressources/"

[[redirects]]
from = "/equipe/marion-rebier/blog/index.html"
to = "/equipe/marion-rebier/ressources/"

[[redirects]]
from = "/projets/index.html"
to = "/photographies/"

[[redirects]]
from = "/portfolio/2006-heros-zapatistes/index.html"
to = "/photographies/2006-heros-zapatistes/"

[[redirects]]
from = "/actualites/index.html"
to = "/ressources/"

